name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter a valid semver version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: 'yarn install'
      - run: 'yarn build'
      - run: 'npm version ${{ github.event.inputs.version }}'
      - run: 'npm publish --dry-run'
      - run: 'git push origin main;git push --tags'
      - name: Detect major version
        run: |
          export COMMERCE_MAJOR=$(echo ${{ github.event.inputs.version }} | sed -r 's/v?([0-9]+)\..*/\1/') >> $GITHUB_ENV
          echo "Detected major $COMMERCE_MAJOR from tag ${{ github.event.inputs.version }}"
          echo "::set-env name=COMMERCE_MAJOR::$COMMERCE_MAJOR"
      - run: 'echo $COMMERCE_MAJOR'

